// Generated by CoffeeScript 1.9.2
(function() {
  var CONF_PATH, KEY, global, queryObj, session,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  KEY = 'SM_TRACK';

  global = window[KEY];

  CONF_PATH = 'http://page.socialmaster.com.cn/wx/sns/config';

  queryObj = function(s) {
    var kv;
    kv = {};
    if (!s) {
      s = location.search;
    }
    if (!s) {
      return kv;
    }
    s = s.slice(1).split('&');
    $.map(s, function(e) {
      var k, ref, v;
      ref = e.split('='), k = ref[0], v = ref[1];
      return kv[k] = decodeURIComponent(v);
    });
    return kv;
  };

  session = {
    get: function(k) {
      return sessionStorage.getItem(k);
    },
    set: function(k, v) {
      sessionStorage.setItem(k, v);
      return v;
    },
    del: function(k) {
      return sessionStorage.removeItem(k);
    }
  };

  $(function() {
    var qs, search, wxid;
    search = session.get(KEY);
    qs = queryObj(search);
    if (!qs.state) {
      return alert('没有发现 state');
    }
    if (!qs.openid) {
      return alert('没有发现 openid');
    }
    wxid = location.host.split('.')[0];
    if (!/^wx\w{16,}/.test(wxid)) {
      return alert('域名错误');
    }
    return $.getJSON(CONF_PATH + (search || '?') + '&callback=?', function(data) {
      var appid, domain, ref;
      if (data.error) {
        return alert(data.error);
      }
      appid = data.appid || data.authorizer_appid;
      domain = $.map(['.page.socialmaster.cn', '.page.besth5.com'], function(e) {
        return appid + e;
      });
      if (ref = location.host, indexOf.call(domain, ref) < 0) {
        return alert('域名错误');
      }
    });
  });

}).call(this);
